# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ferry-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.env.MYSQL_ROOT_PASSWORD | b64enc | quote }}
  MYSQL_USER: {{ .Values.env.MYSQL_USER | b64enc | quote }}
  MYSQL_DATABASE: {{ .Values.env.MYSQL_DATABASE | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.env.MYSQL_PASSWORD | b64enc | quote }}