{{ if .Values.redis.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ferry-redis
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ferry-redis
  template:
    metadata:
      labels:
        app: ferry-redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          command:
            - redis-server
            - "--save"
            - "60"
            - "1"
            - "--loglevel"
            - "warning"
          ports:
            - containerPort: {{ .Values.redis.port }}
          volumeMounts:
            - name: redis-storage
              mountPath: /data
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: ferry-redis-pvc
{{ end }}

