{{ if .Values.redis.enable }}
apiVersion: v1
kind: Service
metadata:
  name: ferry-redis
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
  selector:
    app: ferry-redis
  clusterIP: None
{{ end }}
